const stateCapital = [
  { title: "Goa" },
  { title: "Kolkata" },
  { title: "Andhra Pradesh" },
  { title: "Assam" },
  { title: "Bihar" },
  { title: "Chhattisgarh" },
  { title: "Gujarat" },
  { title: "Haryana" },
  { title: "Himachal Pradesh" },
  { title: "Jharkhand" },
  { title: "Karnataka" },
  { title: "Kerala" },
  { title: "Madhya Pradesh" },
  { title: "Maharashtra" },
  { title: "Manipur" },
  { title: "Meghalaya" },
  { title: "Mizoram" },
  { title: "Nagaland" },
  { title: "Odisha" },
  { title: "Punjab" },
  { title: "Rajasthan	" },
  { title: "Sikkim" },
  { title: "Tamil Nadu" },
  { title: "Telangana" },
  { title: "Tripura" },
  { title: "Uttar Pradesh" },
  { title: "Uttarakhand" },
  { title: "West Bengal" },
  { title: "Kolkata" },
  { title: "Shahpur Baghauni" },
  { title: "Samastipur" },
  { title: "Push" },
  { title: "Tajpur" },
  { title: "Amaravati" },
  { title: "Itanagar" },
  { title: "Dispur" },
  { title: "Patna" },
  { title: "Raipur" },
  { title: "Panaji" },
  { title: "Gandhinagar" },
  { title: "Chandigarh" },
  { title: "Shimla" },
  { title: "Bengaluru" },
  { title: "Thiruvananthapuram" },
  { title: "Bhopal" },
  { title: "Mumbai" },
  { title: "Imphal" },
  { title: "Shillong" },
  { title: "Aizawl" },
  { title: "Kohima" },
  { title: "Bhubaneswar" },
  { title: "Chandigarh" },
  { title: "Jaipur" },
  { title: "Gangtok" },
  { title: "Chennai" },
  { title: "Hyderabad" },
  { title: "Agartala" },
  { title: "Lucknow" },
  { title: "Dehradun" },
  { title: "Gairsain" },
];

export default stateCapital;
